# Generated by Django 4.0.4 on 2022-05-17 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(default='Pepega', max_length=30)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=70)),
                ('age', models.PositiveSmallIntegerField()),
                ('email', models.CharField(blank=True, max_length=70, unique=True)),
                ('profession', models.CharField(max_length=50)),
            ],
        ),
    ]
