# Generated by Django 4.0.4 on 2022-05-25 19:07

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('to_do_list', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='directory_link',
            field=models.URLField(default=uuid.UUID('64982d72-1db5-41fc-b15d-7a9675c4d16b'), verbose_name='Ссылка на директорию'),
        ),
    ]
