# Generated by Django 4.0.4 on 2022-06-01 06:42

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('to_do_list', '0002_project_directory_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='directory_link',
            field=models.URLField(default=uuid.UUID('cd488563-744a-4b0d-8e35-689209045005'), verbose_name='Ссылка на директорию'),
        ),
    ]
