# Generated by Django 4.0.3 on 2022-06-14 13:03

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('to_do_list', '0003_alter_project_directory_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='directory_link',
            field=models.URLField(default=uuid.UUID('460af0a8-7b5c-4a0e-b507-1fbbdcff63fd'), verbose_name='Ссылка на директорию'),
        ),
    ]
