# Generated by Django 4.0.3 on 2022-06-15 15:06

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('to_do_list', '0004_alter_project_directory_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='directory_link',
            field=models.URLField(default=uuid.UUID('dfdf8e9d-a4de-4db6-ad11-b4342b0959ba'), verbose_name='Ссылка на директорию'),
        ),
    ]
