# Generated by Django 4.0.3 on 2022-06-19 11:02

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('to_do_list', '0006_alter_project_directory_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='directory_link',
            field=models.URLField(default=uuid.UUID('a14c09f7-0162-4e53-bfbb-cf3d4b9edb69'), verbose_name='Ссылка на директорию'),
        ),
    ]
