# Generated by Django 4.0.4 on 2022-06-19 11:47

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('to_do_list', '0007_alter_project_directory_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='directory_link',
            field=models.URLField(default=uuid.UUID('dc5ffffa-a9a4-455a-b28a-730abaee9913'), verbose_name='Ссылка на директорию'),
        ),
    ]
